### ISSUE TITLE
Day02 Demo: -[DSStack compressedStack] problem

### ISSUE THREAD

**Issue by sealedace** [renmoqiqi/100-Days-Of-iOS-DataStructure-Algorithm#5]
![image](https://user-images.githubusercontent.com/788553/57440887-66a2cd00-727b-11e9-8041-e1e47c3524b6.png)

I found that you didn't add the data to the new array. So I think it should be replaced like this:

```objc
- (void)compressedStack
{
    NSUInteger capacitySize = (NSUInteger)(self.maxStackSize * 0.9);
    NSUInteger stackSize = self.stackArray.count;
    if (stackSize < capacitySize)
    {
        NSMutableArray *newArray = [[NSMutableArray alloc] initWithCapacity:stackSize];
        for (id object in self.stackArray)
        {
            [newArray addObject:object];
        }
        self.stackArray = newArray;
        self.maxStackSize = stackSize;
    }
}
```

**Comment by renmoqiqi** [comment]
The bug has been fixed

**Comment by renmoqiqi** [comment]
> ![image](https://user-images.githubusercontent.com/788553/57440887-66a2cd00-727b-11e9-8041-e1e47c3524b6.png)
> 
> I found that you didn't add the data to the new array. So I think it should be replaced like this:
> 
> ```objc
> - (void)compressedStack
> {
>     NSUInteger capacitySize = (NSUInteger)(self.maxStackSize * 0.9);
>     NSUInteger stackSize = self.stackArray.count;
>     if (stackSize < capacitySize)
>     {
>         NSMutableArray *newArray = [[NSMutableArray alloc] initWithCapacity:stackSize];
>         for (id object in self.stackArray)
>         {
>             [newArray addObject:object];
>         }
>         self.stackArray = newArray;
>         self.maxStackSize = stackSize;
>     }
> }
> ```

The bug has been fixed

**Comment by renmoqiqi** [comment]
The bug has been fixed
