### ISSUE TITLE
APP为什么要收费呀  就算收费  也有点贵了  

### ISSUE THREAD

**Issue by kdq-github** [renmoqiqi/100-Days-Of-iOS-DataStructure-Algorithm#6]
看了有APP而且上架了  满心欢喜的去打算下载 结果要18元RMB  😀  改为1元如何

**Comment by renmoqiqi** [comment]
老板说你工资有点高，给你改为1元如何

**Comment by renmoqiqi** [comment]
> 看了有APP而且上架了 满心欢喜的去打算下载 结果要18元RMB 😀 改为1元如何

老板说你工资有点高，给你改为1元如何
